[package]
name = "lcel_chain"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
tokio.workspace = true
synaptic = { version = "0.3", path = "../../crates/synaptic", features = ["runnables", "macros"] }
